name: appcolegio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.0
  dio: ^5.3.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icono.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
